basePath: /
host: localhost:4000
info:
  contact: 
    email: support@swagger.io
    name: API support
    url: http://www.swagger.io/support
  description: This is a sample server
  license:
    name: Apache 2.0
    url: http://www.apache.org/license/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Testing API Specification by Fan_herya in Golang
  version: "1.0"
paths: 
  /:
    get:
      consumes:
        -'*/*'
        description: get the status of server
        produces:
          - application/json
          responses:
            "200":
              description: OK
              schema:
                additionalProperties: true
                type: object
          summary: show the status of server
          tags:
            -root
schema:
  -http
swagger: "2.0"
